name: Build Game

on:
    workflow_dispatch:
    push:
        branches:
            - "*"

jobs:
    setupJob:
        runs-on: self-hosted-linux
        steps:
            - name: Make Build Directory
              run: mkdir build

            - name: Clone Repository
              uses: actions/checkout@v3
              with:
                repository: "frenchfrysays3/my-custom-game"
    buildOnLinux:
        runs-on: self-hosted-linux
        needs: setupJob
        steps:
            - name: Setup Cmake version 3.10
              uses: jwlawson/actions-setup-cmake@v2
              with:
                cmake-version: '4.0.2'

            - name: Configure the build
              run: cmake -B build

            - name: Build the program
              run: cmake --build build --config RelWithDebInfo