name: Build Game

on:
    workflow_dispatch:
    push:
        branches:
            - "*"

jobs:
    setupJob:
        runs-on: ubuntu-latest
        steps:
            - name: Go to where code is
              run: cd ..

            - name: Install curl
              run: sudo apt-get install curl -y

            - name: Download the CMakeLists.txt file
              run: curl -o CMakeLists.txt https://raw.githubusercontent.com/frenchfrysays3/My-Custom-Game/refs/heads/main/CMakeLists.txt

    buildOnLinux:
        runs-on: ubuntu-latest
        needs: setupJob
        steps:
            - name: Setup Cmake version 4.0.2
              uses: jwlawson/actions-setup-cmake@v2
              with:
                cmake-version: '4.0.2'

            - name: Configure the build
              run: cmake -B build

            - name: Build the program
              run: cmake --build build --config RelWithDebInfo