name: Build Game

on:
    workflow_dispatch:
    push:
        branches:
            - "*"

jobs:
    buildOnLinux:
        runs-on: ubuntu-latest
        steps:
            - name: Setup Cmake version 3.10
              uses: jwlawson/actions-setup-cmake@v2
              with:
                cmake-version: '3.10.*'

            - name: Make build directory
              run: mkdir build

            - name: Configure the build
              run: cmake -B build

            - name: Build the program
              run: cmake --build build --config RelWithDebInfo