name: Build Game

on:
    workflow_dispatch:
    push:
        branches:
            - "*"

jobs:
    buildOnLinux:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Cmake version 4.0.2
              uses: jwlawson/actions-setup-cmake@v2
              with:
                cmake-version: '4.0.2'

            - name: Configure the build
              run: cmake -B build

            - name: Build the program
              run: cmake --build build --config RelWithDebInfo

            - name: Upload game
              uses: actions/upload-artifact@v4
              with:
                name: game-files
                path: build/RelWithDebInfo/*.exe, build/RelWithDebInfo/*.dll
                if-no-files-found: warn
                retention-days: 90